import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';

export function Header() {
  const router = useRouter();
  const [showMenu, setShowMenu] = useState(false);
  return (
    <>
      <Head>
        <title>PokeDex App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      <nav className="border-gray-200 sticky top-0 drop-shadow-md">
        <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <a href="#" className="flex items-center">
            <Image
              src={'http://localhost:3000/pokemon-logo.png'}
              width={100}
              height={150}
              alt="Logo"
            />
          </a>
          <button
            data-collapse-toggle="navbar-default"
            type="button"
            className="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-white"
            aria-controls="navbar-default"
            aria-expanded="false"
            onClick={() => setShowMenu(!showMenu)}
          >
            <svg
              className="w-6 h-6"
              aria-hidden="true"
              fill="#405794"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fillRule="evenodd"
                d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                clipRule="evenodd"
              ></path>
            </svg>
          </button>
          <div
            className={`${!showMenu ? 'hidden' : ''} w-full md:block md:w-auto`}
          >
            <ul className="font-medium flex flex-col  md:p-0 mt-4  rounded-lg  md:flex-row md:space-x-8 md:mt-0 ">
              <li>
                <a
                  href="#"
                  className="block py-2 pl-3 pr-4 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:hover:bg-white md:dark:hover:bg-transparent"
                  onClick={() => {
                    router.push('/');
                  }}
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="block py-2 pl-3 pr-4 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:hover:bg-white md:dark:hover:bg-transparent"
                  onClick={() => {
                    router.push('/pokedex');
                  }}
                >
                  Pokédex
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </>
  );
}

export function Body({ children }) {
  return <main>{children}</main>;
}
